### ISSUE TITLE
Hosting It.

### ISSUE THREAD

**Issue by smartnavdeep** [shikha12264/Covid-19-NGO-Website-HTML-CSS-JAVASCRIPT-#1]
Well instead of taking the screenshot of your 🕸site and the pasting it in markdown, you can host the website using github for free.

Now scroll down to your settings tab and you can see the options of customizing your website. now I can't write everything down, you can refer the [github docs](https://pages.github.com/) to know more. 

![image](https://user-images.githubusercontent.com/65970997/106907630-78512700-6724-11eb-9d43-0c11c91747ef.png)

Now when customize everything, you need to make sure the the file [HOME.html](https://github.com/shikha12264/Covid-19-NGO-Website-HTML-CSS-JAVASCRIPT-/blob/main/Home.html), must be renamed into `index.html` cuz github takes the index.html file as the landing page of the website.

---

Hope this helps.

Regards,
Navdeep.

**Comment by shikha12264** [comment]
Thanks for your suggestion @smartnavdeep will work on it as soon as possible!!

**Comment by smartnavdeep** [comment]
Well you made the configuration, but you shouldn't keep the source as `/docs`, instead you need to keep the source as `/root`, now when you do it, your website won't be hosted immediately, cause there are many file, but anyways, you need to keep the `/root` as source.

![smartnavdeep_Covid-19-NGO-Website-HTML-CSS-JAVASCRIPT-_ HTML-CSS-JAVASCRIPT Based website - Brave 2021-02-07 19-35-03](https://user-images.githubusercontent.com/65970997/107149026-68cc1b00-697c-11eb-89b3-d9be240be93f.gif)

**Comment by shikha12264** [comment]
Sure but i tried keeping the source as /root yet it didn't work!!
Though am trying to fix it as early as possible.

**Comment by smartnavdeep** [comment]
## Are sure about that? 
![are you sure](https://user-images.githubusercontent.com/65970997/107229669-1e15d600-6a44-11eb-8f2e-ca49e703483b.gif)

here is the link to your website [Click Me!](https://shikha12264.github.io/Covid-19-NGO-Website-HTML-CSS-JAVASCRIPT-), as I said it would take time for github to host you website that's you might have faced the problem.

Anyways the problem is fixed. Hope this helps you : )

---

Regards,
Navdeep.
